name: RemoteControlPanel
version: 1.0.0
main: net.bobmandude9889.bukkit.Main
author: bobmandude9889
depend: [Vault]

permissions:
    remote.access:
        description: "Allows user to register account on remote panel."
        default: OP